<?php

/**
 * @file
 * Contains block_tests.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_tests_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_tests module.
    case 'help.page.block_tests':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Core Block Functionality Tests') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_tests_theme() {
  $theme = [];

  return $theme;
}
